type: object
description: Express sample urgent shipment record
properties:
  id:
    type: integer
    description: Express sample shipment ID
  expressSampleOrderId:
    type: string
    description: Express sample order number
  status:
    type: string
    description: Express sample shipment status
    enum:
      - draft
      - pending
      - approved
      - rejected
      - cancelled
      - booked
      - dispatched
      - delivered
  requestedShipDate:
    type: string
    format: date
    description: 希望出库日期
  desiredDeliveryDate:
    type: string
    format: date
    description: 希望送达日期
  desiredDeliveryTimeWindow:
    type: string
    description: 希望送达时间段
    enum:
      - morning
      - noon
      - afternoon
      - evening
      - anytime
  warehouse:
    type: object
    description: 发货仓库信息
    properties:
      id:
        type: integer
        description: 仓库ID
      name:
        type: string
        description: 仓库名称
  customer:
    type: object
    description: 归属客户信息
    properties:
      id:
        type: integer
        description: 客户ID
      name:
        type: string
        description: 客户名称
  customerContactId:
    type: integer
    description: 客户联系人ID
  recipient:
    type: object
    description: 收件人信息
    properties:
      companyName:
        type: string
        description: 收件公司名称
      department:
        type: string
        description: 收件部门
      name:
        type: string
        description: 收件人姓名
      phoneNumber:
        type: string
        description: 收件人电话
      postalCode:
        type: string
        description: 邮政编码
      prefecture:
        type: string
        description: 都道府县
      city:
        type: string
        description: 市区町村
      addressLine1:
        type: string
        description: 地址行1
      addressLine2:
        type: string
        description: 地址行2
  deliveryService:
    type: string
    description: Express courier service type
    enum:
      - regular
      - cool
      - frozen
      - timeValue
    default: regular
  packageCount:
    type: integer
    description: 包裹箱数
    minimum: 1
  packageType:
    type: string
    description: 包装类型说明
  deliveryFeePayer:
    type: string
    description: 运费承担方
    enum:
      - sender
      - recipient
      - thirdParty
  samplePurpose:
    type: string
    description: 样品发送目的
  emergencyContact:
    type: object
    description: 紧急联系人信息
    properties:
      name:
        type: string
        description: 紧急联系人姓名
      phoneNumber:
        type: string
        description: 紧急联系电话
  carrierName:
    type: string
    description: 承运商名称
  trackingNumber:
    type: string
    description: 追踪编号
  note:
    type: string
    description: 备注
  items:
    type: array
    description: Express sample shipment item list
    items:
      $ref: '../../index.yaml#/components/schemas/ExpressSampleShipmentItem'
  createdAt:
    type: string
    format: date-time
    description: 创建时间
  updatedAt:
    type: string
    format: date-time
    description: 更新时间
  dispatchedAt:
    type: string
    format: date-time
    description: 实际发货时间
  deliveredAt:
    type: string
    format: date-time
    description: 实际送达时间
