get:
  summary: 获取Express Sample出库报告列表
  operationId: listExpressSampleShipmentReports
  tags:
    - Express Sample报告
  description: |
    获取Express Sample出库的历史报告列表，支持按仓库、客户和状态筛选。
  parameters:
    - name: page
      in: query
      description: 页码
      schema:
        type: integer
        default: 1
        minimum: 1
    - name: itemsPerPage
      in: query
      description: 每页数量
      schema:
        type: integer
        default: 20
        minimum: 1
        maximum: 100
    - name: warehouseId
      in: query
      description: 仓库ID筛选
      schema:
        type: integer
    - name: customerId
      in: query
      description: 客户ID筛选
      schema:
        type: integer
    - name: status
      in: query
      description: 报告状态筛选
      schema:
        type: string
        enum:
          - pending
          - processing
          - completed
          - failed
    - name: startDate
      in: query
      description: 报告生成开始日期
      schema:
        type: string
        format: date
    - name: endDate
      in: query
      description: 报告生成结束日期
      schema:
        type: string
        format: date
  responses:
    '200':
      description: 成功获取Express Sample出库报告列表
      content:
        application/json:
          schema:
            $ref: '../../index.yaml#/components/schemas/ExpressSampleShipmentReportListResp'
    '400':
      description: 请求参数错误
    '500':
      description: 服务器内部错误
