get:
  summary: 名义变更商品列表
  operationId: listNameChangeItems
  tags:
    - 库存
  parameters:
    - name: page
      in: query
      description: 页码
      schema:
        type: integer
        default: 1
    - name: itemsPerPage
      in: query
      description: 每页数量
      schema:
        type: integer
        default: 20
    - name: lotNumber
      in: query
      description: 批次号
      schema:
        type: string
    - name: productId
      in: query
      description: 商品ID
      schema:
        type: integer
    - name: nameChangeDateFrom
      in: query
      description: 名义变更日期(From)
      schema:
        type: string
        format: date
    - name: nameChangeDateTo
      in: query
      description: 名义变更日期(To)
      schema:
        type: string
        format: date
  responses:
    '200':
      description: 成功
      content:
        application/json:
          schema:
            $ref: '../../index.yaml#/components/schemas/ListNameChangeItemsResp'
