get:
  summary: 下载名义变更报告
  operationId: downloadNameChangeReport
  tags:
    - 名义变更报告
  description: |
    下载已生成的名义变更报告文件。
    支持PDF和Excel格式的报告下载。
  parameters:
    - name: reportId
      in: path
      required: true
      description: 名义变更报告ID
      schema:
        type: string
  responses:
    '200':
      description: 成功下载名义变更报告文件
      content:
        application/pdf:
          schema:
            type: string
            format: binary
          examples:
            pdf_report:
              summary: PDF格式名义变更报告
        application/vnd.openxmlformats-officedocument.spreadsheetml.sheet:
          schema:
            type: string
            format: binary
          examples:
            excel_report:
              summary: Excel格式名义变更报告
      headers:
        Content-Disposition:
          description: 文件下载附件头
          schema:
            type: string
            example: 'attachment; filename="name_change_report_20240115.pdf"'
        Content-Length:
          description: 文件大小
          schema:
            type: integer
    '404':
      description: 报告不存在或尚未生成完成
    '410':
      description: 下载链接已过期
    '500':
      description: 服务器内部错误
