get:
  summary: 出库单详情
  operationId: getOutbound
  tags:
    - 库存
  parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
        format: int32
        description: 入库单ID
  responses:
    '200':
      description: 成功
      content:
        application/json:
          schema:
            $ref: '../../index.yaml#/components/schemas/Outbound'

put:
  summary: 更新出库单
  operationId: updateOutbound
  tags:
    - 库存
  parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
        format: int32
        description: 出库单ID
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '../../index.yaml#/components/schemas/Outbound'
  responses:
    '200':
      description: 成功
      content:
        application/json:
          schema:
            $ref: '../../index.yaml#/components/schemas/Outbound'
delete:
  summary: 删除出库单
  operationId: deleteOutbound
  tags:
    - 库存
  parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
        format: int32
        description: 出库单ID
