post:
  summary: 拒绝出库单
  operationId: rejectOutbound
  tags:
    - 库存
  parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
        format: int32
        description: 出库单ID
  responses:
    '200':
      description: 成功
      content:
        application/json:
          schema:
            $ref: '../../index.yaml#/components/schemas/Outbound'
