get:
  summary: 出库单列表
  operationId: listOutbounds
  tags:
    - 库存
  parameters:
    - name: page
      in: query
      description: 页码
      schema:
        type: integer
        default: 1
    - name: itemsPerPage
      in: query
      description: 每页数量
      schema:
        type: integer
        default: 20
  responses:
    '200':
      description: 成功
      content:
        application/json:
          schema:
            $ref: '../../index.yaml#/components/schemas/ListOutboundsResp'
