get:
  summary: 获取出库报告生成状态
  operationId: getOutboundReportStatus
  tags:
    - 出库报告
  description: |
    根据报告ID获取出库报告的生成状态。
    可用于轮询检查报告是否生成完成。
  parameters:
    - name: reportId
      in: path
      required: true
      description: 出库报告ID
      schema:
        type: string
  responses:
    '200':
      description: 成功获取出库报告状态
      content:
        application/json:
          schema:
            $ref: '../../index.yaml#/components/schemas/OutboundReport'
    '404':
      description: 报告不存在
    '500':
      description: 服务器内部错误
