openapi: '3.1.0'
info:
  title: '库存管理系统接口'
  version: '0.0.1'

servers:
  - url: https://development.gigantic-server.com/v1
    description: Development server
  - url: https://staging.gigantic-server.com/v1
    description: Staging server
  - url: https://api.gigantic-server.com/v1
    description: Production server

security:
  - oauth2: []
  - bearerAuth: []

paths:
  # 仪表盘
  /dashboard/stats:
    $ref: './paths/dashboard/stats.yaml'

  # 仓库接口
  /warehouses:
    $ref: './paths/warehouse/list.yaml'
  /warehouse:
    $ref: './paths/warehouse/create.yaml'
  /warehouse/{id}:
    $ref: './paths/warehouse/id.yaml'

  # 商品接口
  /products:
    $ref: './paths/product/list.yaml'
  /product:
    $ref: './paths/product/create.yaml'
  /product/{id}:
    $ref: './paths/product/id.yaml'

  # 客户接口
  /customers:
    $ref: './paths/customer/list.yaml'
  /customer:
    $ref: './paths/customer/create.yaml'
  /customer/{id}:
    $ref: './paths/customer/id.yaml'

  # 入库
  /inventory/inbounds:
    $ref: './paths/inventory/inboundList.yaml'
  /inventory/inbound:
    $ref: './paths/inventory/inbound.yaml'
  /inventory/inbound/{id}:
    $ref: './paths/inventory/inboundId.yaml'
  /inventory/inbound/{id}/approve:
    $ref: './paths/inventory/inboundApprove.yaml'
  /inventory/inbound/{id}/reject:
    $ref: './paths/inventory/inboundReject.yaml'
  /inventory/inbound/{id}/cancel:
    $ref: './paths/inventory/inboundCancel.yaml'
  /inventory/inboundItems:
    $ref: './paths/inventory/inboundItemList.yaml'

  # 出库
  /inventory/outbounds:
    $ref: './paths/inventory/outboundList.yaml'
  /inventory/outbound:
    $ref: './paths/inventory/outbound.yaml'
  /inventory/outbound/{id}:
    $ref: './paths/inventory/outboundId.yaml'
  /inventory/outbound/{id}/approve:
    $ref: './paths/inventory/outboundApprove.yaml'
  /inventory/outbound/{id}/reject:
    $ref: './paths/inventory/outboundReject.yaml'
  /inventory/outbound/{id}/cancel:
    $ref: './paths/inventory/outboundCancel.yaml'
  /inventory/outboundItems:
    $ref: './paths/inventory/outboundItemList.yaml'

  # 在库
  /inventory/list:
    $ref: './paths/inventory/list.yaml'
  /inventory/item/{id}:
    $ref: './paths/inventory/detail.yaml'
  /inventory/agedItems:
    $ref: './paths/inventory/agedInventoryItems.yaml'
  /inventory/agedItems/{id}/mute:
    $ref: './paths/inventory/muteAgedInventoryItem.yaml'

  # 在库报告
  /inventory/reports:
    $ref: './paths/inventory/reportList.yaml'
  /inventory/report/generate:
    $ref: './paths/inventory/generateReport.yaml'
  /inventory/reports/{reportId}/status:
    $ref: './paths/inventory/reportStatus.yaml'
  /inventory/reports/{reportId}/download:
    $ref: './paths/inventory/reportDownload.yaml'

  # 入库报告
  /inventory/inboundReports:
    $ref: './paths/inventory/inboundReportList.yaml'
  /inventory/inboundReport/generate:
    $ref: './paths/inventory/generateInboundReport.yaml'
  /inventory/inboundReports/{reportId}/status:
    $ref: './paths/inventory/inboundReportStatus.yaml'
  /inventory/inboundReports/{reportId}/download:
    $ref: './paths/inventory/inboundReportDownload.yaml'

  # 出库报告
  /inventory/outboundReports:
    $ref: './paths/inventory/outboundReportList.yaml'
  /inventory/outboundReport/generate:
    $ref: './paths/inventory/generateOutboundReport.yaml'
  /inventory/outboundReports/{reportId}/status:
    $ref: './paths/inventory/outboundReportStatus.yaml'
  /inventory/outboundReports/{reportId}/download:
    $ref: './paths/inventory/outboundReportDownload.yaml'

  # 名义变更
  /inventory/nameChanges:
    $ref: './paths/inventory/nameChangeList.yaml'
  /inventory/nameChange:
    $ref: './paths/inventory/nameChange.yaml'
  /inventory/nameChange/{id}:
    $ref: './paths/inventory/nameChangeId.yaml'
  /inventory/nameChange/{id}/approve:
    $ref: './paths/inventory/nameChangeApprove.yaml'
  /inventory/nameChange/{id}/reject:
    $ref: './paths/inventory/nameChangeReject.yaml'
  /inventory/nameChange/{id}/cancel:
    $ref: './paths/inventory/nameChangeCancel.yaml'
  /inventory/nameChangeItems:
    $ref: './paths/inventory/nameChangeItemList.yaml'

  # 名义变更报告
  /inventory/nameChangeReports:
    $ref: './paths/inventory/nameChangeReportList.yaml'
  /inventory/nameChangeReport/generate:
    $ref: './paths/inventory/generateNameChangeReport.yaml'
  /inventory/nameChangeReports/{reportId}/status:
    $ref: './paths/inventory/nameChangeReportStatus.yaml'
  /inventory/nameChangeReports/{reportId}/download:
    $ref: './paths/inventory/nameChangeReportDownload.yaml'

  # 集装箱
  /containers:
    $ref: './paths/container/list.yaml'
  /container:
    $ref: './paths/container/create.yaml'
  /container/{id}:
    $ref: './paths/container/id.yaml'

components:
  securitySchemes:
    # 这里是swagger-codegen已知问题的workaround，实际不需要oauth2认证
    oauth2:
      type: oauth2
      flows:
        password:
          tokenUrl: /auth/login
          scopes: { }
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    # 通用
    Address:
      $ref: './schemas/common/Address.yaml'
    Pagination:
      $ref: './schemas/common/Pagination.yaml'
    # 仪表盘
    DashboardStats:
      $ref: './schemas/dashboard/DashboardStats.yaml'
    DashboardStatsResp:
      $ref: './schemas/dashboard/DashboardStatsResp.yaml'
    # 仓库
    Warehouse:
      $ref: './schemas/warehouse/Warehouse.yaml'
    CreateWarehouseReq:
      $ref: './schemas/warehouse/CreateWarehouseReq.yaml'
    CreateWarehouseResp:
      $ref: './schemas/warehouse/CreateWarehouseResp.yaml'
    GetWarehouseResp:
      $ref: './schemas/warehouse/GetWarehouseResp.yaml'
    ListWarehousesResp:
      $ref: './schemas/warehouse/ListWarehousesResp.yaml'
    # 商品
    Product:
      $ref: './schemas/product/Product.yaml'
    ProductCategory:
      $ref: './schemas/product/ProductCategory.yaml'
    CreateProductReq:
      $ref: './schemas/product/CreateProductReq.yaml'
    CreateProductResp:
      $ref: './schemas/product/CreateProductResp.yaml'
    GetProductResp:
      $ref: './schemas/product/GetProductResp.yaml'
    ListProductsResp:
      $ref: './schemas/product/ListProductsResp.yaml'
    # 客户
    Customer:
      $ref: './schemas/customer/Customer.yaml'
    CreateCustomerReq:
      $ref: './schemas/customer/CreateCustomerReq.yaml'
    CreateCustomerResp:
      $ref: './schemas/customer/CreateCustomerResp.yaml'
    GetCustomerResp:
      $ref: './schemas/customer/GetCustomerResp.yaml'
    ListCustomersResp:
      $ref: './schemas/customer/ListCustomersResp.yaml'
    CustomerContact:
      $ref: './schemas/customer/CustomerContact.yaml'
    # 库存
    InventoryItem:
      $ref: './schemas/inventory/InventoryItem.yaml'
    InventoryItemDetailResp:
      $ref: './schemas/inventory/InventoryItemDetailResp.yaml'
    AgedInventoryItemListResp:
      $ref: './schemas/inventory/AgedInventoryItemListResp.yaml'
    ListInventoryResp:
      $ref: './schemas/inventory/ListInventoryResp.yaml'
    StorageFeePlan:
      $ref: './schemas/inventory/StorageFeePlan.yaml'
    Inbound:
      $ref: './schemas/inventory/Inbound.yaml'
    ListInboundsResp:
      $ref: './schemas/inventory/ListInboundsResp.yaml'
    ListInboundItemsResp:
      $ref: './schemas/inventory/ListInboundItemsResp.yaml'
    InboundItem:
      $ref: './schemas/inventory/InboundItem.yaml'
    Outbound:
      $ref: './schemas/inventory/Outbound.yaml'
    ListOutboundsResp:
      $ref: './schemas/inventory/ListOutboundsResp.yaml'
    ListOutboundItemsResp:
      $ref: './schemas/inventory/ListOutboundItemsResp.yaml'
    OutboundItem:
      $ref: './schemas/inventory/OutboundItem.yaml'
    # 在库报告
    InventoryReportReq:
      $ref: './schemas/inventory/InventoryReportReq.yaml'
    InventoryReportResp:
      $ref: './schemas/inventory/InventoryReportResp.yaml'
    InventoryReport:
      $ref: './schemas/inventory/InventoryReport.yaml'
    InventoryReportListResp:
      $ref: './schemas/inventory/InventoryReportListResp.yaml'
    # 入库报告
    InboundReportReq:
      $ref: './schemas/inventory/InboundReportReq.yaml'
    InboundReportResp:
      $ref: './schemas/inventory/InboundReportResp.yaml'
    InboundReport:
      $ref: './schemas/inventory/InboundReport.yaml'
    InboundReportListResp:
      $ref: './schemas/inventory/InboundReportListResp.yaml'
    # 出库报告
    OutboundReportReq:
      $ref: './schemas/inventory/OutboundReportReq.yaml'
    OutboundReportResp:
      $ref: './schemas/inventory/OutboundReportResp.yaml'
    OutboundReport:
      $ref: './schemas/inventory/OutboundReport.yaml'
    OutboundReportListResp:
      $ref: './schemas/inventory/OutboundReportListResp.yaml'
    # 名义变更
    NameChange:
      $ref: './schemas/inventory/NameChange.yaml'
    ListNameChangesResp:
      $ref: './schemas/inventory/ListNameChangesResp.yaml'
    ListNameChangeItemsResp:
      $ref: './schemas/inventory/ListNameChangeItemsResp.yaml'
    NameChangeItem:
      $ref: './schemas/inventory/NameChangeItem.yaml'
    # 名义变更报告
    NameChangeReportReq:
      $ref: './schemas/inventory/NameChangeReportReq.yaml'
    NameChangeReportResp:
      $ref: './schemas/inventory/NameChangeReportResp.yaml'
    NameChangeReport:
      $ref: './schemas/inventory/NameChangeReport.yaml'
    NameChangeReportListResp:
      $ref: './schemas/inventory/NameChangeReportListResp.yaml'
    # 集装箱
    Container:
      $ref: './schemas/container/Container.yaml'
    ContainerItem:
      $ref: './schemas/container/ContainerItem.yaml'
    ListContainersResp:
      $ref: './schemas/container/ListContainersResp.yaml'
    CreateContainerReq:
      $ref: './schemas/container/CreateContainerReq.yaml'
    CreateContainerResp:
      $ref: './schemas/container/CreateContainerResp.yaml'
    GetContainerResp:
      $ref: './schemas/container/GetContainerResp.yaml'