openapi: '3.1.0'
info:
  title: '库存管理系统接口'
  version: '0.0.1'

servers:
  - url: https://development.gigantic-server.com/v1
    description: Development server
  - url: https://staging.gigantic-server.com/v1
    description: Staging server
  - url: https://api.gigantic-server.com/v1
    description: Production server

security:
  - oauth2: []
  - bearerAuth: []

paths:
  # 仓库接口
  /warehouses:
    $ref: './paths/warehouse/list.yaml'
  /warehouse:
    $ref: './paths/warehouse/create.yaml'
  /warehouse/{id}:
    $ref: './paths/warehouse/id.yaml'

  # 商品接口
  /products:
    $ref: './paths/product/list.yaml'
  /product:
    $ref: './paths/product/create.yaml'
  /product/{id}:
    $ref: './paths/product/id.yaml'

  # 客户接口
  /customers:
    $ref: './paths/customer/list.yaml'
  /customer:
    $ref: './paths/customer/create.yaml'
  /customer/{id}:
    $ref: './paths/customer/id.yaml'

  # 入库
  /inventory/inbounds:
    $ref: './paths/inventory/inboundList.yaml'
  /inventory/inbound:
    $ref: './paths/inventory/inbound.yaml'
  /inventory/inbound/{id}:
    $ref: './paths/inventory/inboundId.yaml'
  /inventory/inbound/{id}/approve:
    $ref: './paths/inventory/inboundApprove.yaml'
  /inventory/inbound/{id}/reject:
    $ref: './paths/inventory/inboundReject.yaml'
  /inventory/inbound/{id}/cancel:
    $ref: './paths/inventory/inboundCancel.yaml'
  /inventory/inboundItems:
    $ref: './paths/inventory/inboundItemList.yaml'

  # 出库
  /inventory/outbounds:
    $ref: './paths/inventory/outboundList.yaml'
  /inventory/outbound:
    $ref: './paths/inventory/outbound.yaml'
  /inventory/outbound/{id}:
    $ref: './paths/inventory/outboundId.yaml'
  /inventory/outbound/{id}/approve:
    $ref: './paths/inventory/outboundApprove.yaml'
  /inventory/outbound/{id}/reject:
    $ref: './paths/inventory/outboundReject.yaml'
  /inventory/outbound/{id}/cancel:
    $ref: './paths/inventory/outboundCancel.yaml'

  # 在库
  /inventory/list:
    $ref: './paths/inventory/list.yaml'

components:
  securitySchemes:
    # 这里是swagger-codegen已知问题的workaround，实际不需要oauth2认证
    oauth2:
      type: oauth2
      flows:
        password:
          tokenUrl: /auth/login
          scopes: { }
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    # 通用
    Address:
      $ref: './schemas/common/Address.yaml'
    Pagination:
      $ref: './schemas/common/Pagination.yaml'
    # 仓库
    Warehouse:
      $ref: './schemas/warehouse/Warehouse.yaml'
    CreateWarehouseReq:
      $ref: './schemas/warehouse/CreateWarehouseReq.yaml'
    CreateWarehouseResp:
      $ref: './schemas/warehouse/CreateWarehouseResp.yaml'
    GetWarehouseResp:
      $ref: './schemas/warehouse/GetWarehouseResp.yaml'
    ListWarehousesResp:
      $ref: './schemas/warehouse/ListWarehousesResp.yaml'
    # 商品
    Product:
      $ref: './schemas/product/Product.yaml'
    ProductCategory:
      $ref: './schemas/product/ProductCategory.yaml'
    CreateProductReq:
      $ref: './schemas/product/CreateProductReq.yaml'
    CreateProductResp:
      $ref: './schemas/product/CreateProductResp.yaml'
    GetProductResp:
      $ref: './schemas/product/GetProductResp.yaml'
    ListProductsResp:
      $ref: './schemas/product/ListProductsResp.yaml'
    # 客户
    Customer:
      $ref: './schemas/customer/Customer.yaml'
    CreateCustomerReq:
      $ref: './schemas/customer/CreateCustomerReq.yaml'
    CreateCustomerResp:
      $ref: './schemas/customer/CreateCustomerResp.yaml'
    GetCustomerResp:
      $ref: './schemas/customer/GetCustomerResp.yaml'
    ListCustomersResp:
      $ref: './schemas/customer/ListCustomersResp.yaml'
    CustomerContact:
      $ref: './schemas/customer/CustomerContact.yaml'
    # 库存
    InventoryItem:
      $ref: './schemas/inventory/InventoryItem.yaml'
    ListInventoryResp:
      $ref: './schemas/inventory/ListInventoryResp.yaml'
    StorageFeePlan:
      $ref: './schemas/inventory/StorageFeePlan.yaml'
    Inbound:
      $ref: './schemas/inventory/Inbound.yaml'
    ListInboundsResp:
      $ref: './schemas/inventory/ListInboundsResp.yaml'
    ListInboundItemsResp:
      $ref: './schemas/inventory/ListInboundItemsResp.yaml'
    InboundItem:
      $ref: './schemas/inventory/InboundItem.yaml'
    Outbound:
      $ref: './schemas/inventory/Outbound.yaml'
    ListOutboundsResp:
      $ref: './schemas/inventory/ListOutboundsResp.yaml'
    OutboundItem:
      $ref: './schemas/inventory/OutboundItem.yaml'
